### ISSUE TITLE
Incorrect compare link after push -f

### ISSUE THREAD

**Issue by prichodko** [git-friendly/git-friendly#65]
I found a little issue, when I was using `push -f`.

## Problem:
The message when performing `push -f` looks like this:
```bash
To https://github.com/prichodko/git-friendly.git + ed8ab76...7bf3ef7 docs/bash-autocompletion -> docs/bash-autocompletion (forced update)
```
Notice that there is an additional **+** apart from regular push, which results into this compare link:

```
https://github.com/prichodko/git-friendly/compare/+
```

## Solution
On this [line](https://github.com/jamiew/git-friendly/blob/master/push#L50) print `$4` when force pushing. 

I am just not sure if this is a good solution and doesn't break this functionality for someone else. Otherwise I can send a PR.

git version: `2.14.3`

**Comment by sapegin** [comment]
Yeah, I can reproduce it:

```
To <...>
 + 45669018c86...75f3a8381e7 combine_war_pages_translate_pt_15196926 -> combine_war_pages_translate_pt_15196926 (forced update)
```

Feel free to send a PR!

**Comment by jamiew** [comment]
Just catching up on this. So this would only apply if `-f` (or other args) are specified, right?

What's the best way to write unit tests for bash scripts? :)

**Comment by jamiew** [comment]
OK, I noodled around and could also reproduce this:

On a fresh checkout of this repository:

```
branch testing-issue-65
push
```
-> https://github.com/jamiew/git-friendly/compare/master...testing-issue-65-again
(working)

```
git commit --allow-empty -m "Nothing to see here"
push
```
-> https://github.com/jamiew/git-friendly/compare/4288ffe...3c23281
(working)

```
git reset --soft HEAD^
push -f
```
-> https://github.com/jamiew/git-friendly/compare/+
(broken)

Hack version might be to explicitly try and parse out these "+"?

I wonder if there's a more machine-friendly version of `git push`? I'm not sure what other modifiers might get snuck into that line we're grabbing

**Comment by jamiew** [comment]
closing some old tickets <3 we have a 2 others related to issues w/ bad compare URLs on push and will leave those open
