### ISSUE TITLE
Add test coverage using `bats`

### ISSUE THREAD

**Issue by jamiew** [git-friendly/git-friendly#82]
Looks promising: https://github.com/sstephenson/bats

Would be a little tricky since `push` and other commands require a real remote, but maybe we could use a local checkout as a remote? I haven't mucked around with that but seems like it'd work in principle. 

Might be tricky to test anything that's looking for "github.com" too

**Comment by sapegin** [comment]
I was thinking about using is in another project, but didn't have time to actually try ;-)

**Comment by jamiew** [comment]
closing some old tickets <3
