### ISSUE TITLE
pull failing on master branch

### ISSUE THREAD

**Issue by maxwell** [git-friendly/git-friendly#91]
Not sure if this is a bug or tech support, sorry!

Recently, my ```pull``` command stopped fetching my ``master`` branch

ie
```
➜  BackerKit git:(master) pull 
🚀  Fetching from ....
From .
 * branch                  master     -> FETCH_HEAD
From .
 * branch                  master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
🦄  Done
```

but calling 
```git pull --rebase origin master```

Actually pulls down the new changes. 

Did some low level thing stopped getting tracked in git that maybe GIT FRIENDLY uses?  did maybe I upgrade git and forget to set a new setting or something?  Any help would be much appreciated.

**Comment by jamiew** [comment]
Hello fellow user

I think this means your upstream for the `master` branch has been changed to something besides `origin/master`, or is possibly blank, which `pull` is supposed to fix.

Could you paste output from `git branch -vv` from that directory?

Here is mine for my git-friendly dir -- you can see the upstream in blue 

<img width="1189" alt="Screen Shot 2020-08-14 at 9 47 22 AM" src="https://user-images.githubusercontent.com/1903/90256184-5335c880-de13-11ea-9f0f-eb2c0dfca8b2.png">

**Comment by maxwell** [comment]
Got it! That was it.  My local master somehow stopped tracking ``origin``

For my future fellow search engine travelers fix was to re-track my master branch with

```
git branch -u origin/master master
```
