### ISSUE TITLE
Redundant git-fetch, then git-pull if submodule.recursive = true

### ISSUE THREAD

**Issue by borestad** [git-friendly/git-friendly#93]
A bit of a cornercase, but these lines ...

https://github.com/git-friendly/git-friendly/blob/7cc27e06a86dcf75b428e6b2f9bcbec7e471c0e7/pull#L90
https://github.com/git-friendly/git-friendly/blob/7cc27e06a86dcf75b428e6b2f9bcbec7e471c0e7/pull#L94

Causes submodules to be fetched twice if submodule.recursive = true in my .gitconfig

Example of the issue.

![image](https://user-images.githubusercontent.com/286455/97013608-8306f800-1549-11eb-8384-251fde3d1d49.png)

And ...unless I may be totally off .... shouldn't just a git pull be enough for every case (submodules or not)?

**Comment by jamiew** [comment]
Nice catch. From what I recall offhand "pull" is functionally "fetch + merge", so I think you might be right. I'm not sure what the extra fetch is doing in this case

**Comment by jamiew** [comment]
@borestad is that repo public and I could use as a test case? Will try to replicate otherwise if not

**Comment by jamiew** [comment]
@borestad so I did a couple of tests with this and the only thing I can think of would be to check for the presence of this config var and skip the `git submodule update` if so. Something like:

```
if [ $(git config --global submodule.recurse) -ne "true" ]; then
  git submodule update || rollback $?
fi
```
(untested)

I like idea of keeping the submodule update in there as a "smart default" but not double-pulling

**Comment by jamiew** [comment]
Second update. Per your note looks like both `fetch` and `pull` try to recurse submodules if set, so my wrapper around `submodule update` doesn't really help either

WDYT of forcibly doing:

```
git fetch --no-recurse-submodules
```

and possibly similar for `git pull`, then doing `submodule update` per usual

Starting to get weird

**Comment by borestad** [comment]
> git fetch --no-recurse-submodules

I think this is probably the absolute most fail-safe approach. 
Then there's no cornercase scenarios like in this code:


```
if [ $(git config --global submodule.recurse) -ne "true" ]; then
  git submodule update || rollback $?
fi

```
... where if submodule.recurse would be false in global config, but true in local config 🙃

On the other hand, it *would* work if you just removed the `--global` flag since it will make a recursive lookup from local => global => system config

**Comment by borestad** [comment]
> @borestad is that repo public and I could use as a test case? Will try to replicate otherwise if not

Sorry about slow response for this one. In this particular case, I used this repository:

https://github.com/sorin-ionescu/prezto

**Comment by jamiew** [comment]
Thanks @borestad. I haven't used submodules much, and never recursive ones. I noticed that a `git pull` with submodule.recurse=true seems to have different output than `git submodule update --recursive` -- are they actually equivalent? See #94 for a rough draft fix, but I'm not sure if it actually produces the correct behavior

**Comment by borestad** [comment]
Hi!

This is me, not having to had run the code. But I'd say **no** - not exactly, since 
* `git submodule update --recursive` implies *only* updating the submodule(s)
* `git pull` also fetch/merge/rebase the main repository

**Comment by borestad** [comment]
But ....also. I'm not sure why you need to run a fetch at all here? (the commands name is pull after all)

![image](https://user-images.githubusercontent.com/286455/97423669-e315e980-190f-11eb-85f9-9022b519fcd1.png)

**Comment by jamiew** [comment]
@borestad would you mind giving #94 a try? It works in my tests but I am not a submodule pro

Nice catch on the extra fetch. I was able to turn these 3 commands into just one
