### ISSUE TITLE
Rename our "master" branch to "main"

### ISSUE THREAD

**Issue by jamiew** [git-friendly/git-friendly#98]
I've been doing this in many repositories I rename. This can be confusing for other developers following along. I would be ok to sort of keep `master` in place but move default and new development to `main`, and then later delete master. Or preferably just pull the band-aid. Input welcome!

**Comment by sapegin** [comment]
I think it would be more confusing to have two branches and use only one ;-)

**Comment by jamiew** [comment]
@sapegin cool, I think you are one of the main raw-git users, so if cool with you I will just switch it :)

**Comment by sapegin** [comment]
👍

**Comment by jamiew** [comment]
This is done
